apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
        - name: bookmyshow-container
          # This matches the image tag in your Jenkinsfile
          image: charan027/bookmyshow:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 #THIS to match your Dockerfile EXPOSE port
