apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
spec:
  type: LoadBalancer
  selector:
    app: bookmyshow
  ports:
    - port: 80 # The port you access in the browser
      targetPort: 80 # <--- MUST MATCH the containerPort in deployment.yaml
