apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
    - port: 80 # The port you access in the browser
      targetPort: 3000 # <--- MUST MATCH the containerPort in deployment.yaml
